# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debc3c3dfe3c5e009ff76b79a4e8c7876b71c52f96d2d81bd4bdd6db7193454f6e722affb9c6301a68838c2d9ce0b2b255e1ebafbd99919c05a89b73d45571ea

test:
  secret_key_base: 198bf25d2fbe41448b6e11248a6053d3e6064ed0c3fc37f3aa50d7b624474ab0dc6b9d44a84ace12b2a64b801dc14fe0b653f375a48cd62c62fa01d95f839b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
